Repository jetstack/navigator, pull requests merged in 2018-03, with the labels that each got.

#270 Move seed pod labelling to a separate controller
  hack/e2e.sh
  pkg/controllers/cassandra/cassandra.go
  pkg/controllers/cassandra/cluster_control.go
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/seedlabeller/control.go
  pkg/controllers/cassandra/seedlabeller/control_test.go
  pkg/controllers/cassandra/service/seedprovider/resource.go
  pkg/controllers/cassandra/testing/testing.go
  pkg/controllers/cassandra/util/util.go
Labels: approved, lgtm, release-note-none, size/L

#269 Move rack and datacenter defaulting to API
  pkg/apis/navigator/v1alpha1/defaults.go
  pkg/apis/navigator/v1alpha1/zz_generated.defaults.go
  pkg/controllers/cassandra/nodepool/resource.go
Labels: approved, lgtm, release-note-none, size/M

#249 Add apiserver.persistence config stanza to helm chart
  contrib/charts/navigator/templates/apiserver-pvc.yaml
  contrib/charts/navigator/templates/apiserver.yaml
  contrib/charts/navigator/values.yaml
Labels: approved, lgtm, release-note, size/M

#275 Run jmx_exporter on cassandra nodes to expose metrics
  Dockerfile.pilot-cassandra
  hack/e2e.sh
  hack/libe2e.sh
  pkg/controllers/cassandra/nodepool/resource.go
Labels: approved, lgtm, release-note, size/M

#267 Add doc on multi-az cassandra deployments
  docs/cassandra/multi-az.md
  hack/verify-links.sh
Labels: approved, lgtm, release-note-none, size/L

#273 Initial sphinx documentation
  Makefile
  README.md
  docs/Makefile
  docs/cassandra.rst
  docs/cassandra/multi-az.md
  docs/conf.py
  docs/developing.rst
  docs/dictionary.txt
  docs/elasticsearch.rst
  docs/images/arch.jpg
  docs/images/demo.gif
  docs/index.rst
  docs/quick-start.rst
  docs/quick-start/README.md
  docs/quick-start/deployment-navigator.yaml
  docs/quick-start/storage-class.yaml
  docs/requirements.txt
  docs/supported-types/README.md
  docs/supported-types/cassandra-cluster.md
  docs/supported-types/elasticsearch-cluster.md
  hack/verify-errexit.sh
Labels: approved, lgtm, release-note-none, size/XL

#263 Report the actual Cassandra Version
  hack/e2e.sh
  hack/libe2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/validation/cassandra_test.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/cassandra/nodetool/client/client.go
  pkg/cassandra/nodetool/fake/fake.go
  pkg/cassandra/nodetool/nodetool.go
  pkg/cassandra/nodetool/nodetool_test.go
  pkg/cassandra/version/version.go
  pkg/cassandra/version/version_test.go
  pkg/controllers/cassandra/nodepool/util.go
  pkg/pilot/cassandra/v3/pilot.go
  pkg/pilot/cassandra/v3/pilot_test.go
Labels: approved, lgtm, release-note-none, size/XL

#281 Remove Couchbase line from README.md
  README.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#282 Allow Cassandra NodePools to be configured with resource requests and limits.
  contrib/charts/navigator/templates/controller.yaml
  contrib/charts/navigator/templates/leaderelection-endpoint.yaml
  docs/cassandra.rst
  docs/quick-start/cassandra-cluster.yaml
  hack/e2e.sh
  hack/libe2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/controllers/cassandra/nodepool/resource.go
Labels: approved, lgtm, release-note-none, size/M

#278 Remove the loadbalanced CQL service and document an alternative way to connect.
  docs/cassandra.rst
  docs/quick-start/cassandra-cluster.yaml
  hack/e2e.sh
  hack/libe2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  internal/test/unit/framework/state_fixture.go
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/controllers/cassandra/cassandra.go
  pkg/controllers/cassandra/cluster_control.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/seedlabeller/control.go
  pkg/controllers/cassandra/seedlabeller/control_test.go
  pkg/controllers/cassandra/service/control.go
  pkg/controllers/cassandra/service/control_test.go
  pkg/controllers/cassandra/service/cql/control.go
  pkg/controllers/cassandra/service/cql/control_test.go
  pkg/controllers/cassandra/service/cql/resource.go
  pkg/controllers/cassandra/service/seedprovider/control.go
  pkg/controllers/cassandra/service/seedprovider/control_test.go
  pkg/controllers/cassandra/service/seedprovider/resource.go
  pkg/controllers/cassandra/service/testing/testing.go
  pkg/controllers/cassandra/service/util/util.go
  pkg/controllers/cassandra/testing/testing.go
  pkg/controllers/cassandra/util/util.go
  pkg/controllers/executor.go
Labels: approved, lgtm, release-note-none, size/XL

#276 Configurable scheduler
  docs/cassandra.rst
  docs/configure-scheduler.rst
  docs/dictionary.txt
  docs/elasticsearch.rst
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
Labels: approved, lgtm, release-note, size/M

#283 Make nodepool persistence settings immutable
  docs/cassandra.rst
  docs/dictionary.txt
  docs/elasticsearch.rst
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/validation/cassandra_test.go
  pkg/apis/navigator/validation/elasticsearch.go
  pkg/apis/navigator/validation/elasticsearch_test.go
  pkg/apis/navigator/validation/generic_test.go
  pkg/registry/navigator/escluster/strategy.go
Labels: approved, lgtm, release-note-none, size/L

#284 Add limits as well requests to all Navigator pod containers.
  contrib/charts/navigator/values.yaml
  docs/cassandra.rst
  docs/elasticsearch.rst
  docs/managing-compute-resources.rst
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
  hack/libe2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  hack/testdata/es-cluster-test.template.yaml
  hack/testdata/values.yaml
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
Labels: approved, lgtm, release-note-none, size/M

#287 Remove the sysctl feature and add documentation instead
  docs/dictionary.txt
  docs/elasticsearch.rst
  docs/quick-start.rst
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
  docs/quick-start/sysctl-daemonset.yaml
  hack/prepare-e2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  hack/testdata/es-cluster-test.template.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/validation/elasticsearch_test.go
  pkg/apis/navigator/validation/generic.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
Labels: approved, lgtm, release-note-none, size/L

#290 Use int32 for Cassandra Replicas and ReadyReplicas
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
Labels: approved, lgtm, release-note-none, size/XS

#296 Remove duplicate Int32Ptr and Int64Ptr functions
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/util/util.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
  pkg/controllers/elasticsearch/actions/scale_test.go
  pkg/controllers/elasticsearch/actions/update_version_test.go
  pkg/controllers/elasticsearch/role/controller_test.go
  pkg/controllers/elasticsearch/rolebinding/controller_test.go
  pkg/controllers/elasticsearch/util/util.go
  pkg/util/ptr/util.go
Labels: approved, lgtm, release-note-none, size/L

#298 Increase the memory limit for pilot init containers
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
Labels: approved, lgtm, release-note-none, size/XS

#293 Use new unit test fixture for nodepool control tests
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/nodepool/nodepool_test.go
Labels: approved, lgtm, release-note-none, size/L

#299 Update CassandraCluster.Status.NodePools
  contrib/charts/navigator/templates/rbac.yaml
  hack/e2e.sh
  pkg/controllers/cassandra/cassandra.go
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/nodepool/nodepool_test.go
  pkg/controllers/cassandra/util/util.go
Labels: approved, lgtm, release-note-none, size/L

#291 Use new test fixture in Cassandra controls
  docs/cassandra.rst
  docs/elasticsearch.rst
  docs/supplementary-resources.rst
  internal/test/unit/framework/state_fixture.go
  pkg/controllers/cassandra/role/control.go
  pkg/controllers/cassandra/role/control_test.go
  pkg/controllers/cassandra/rolebinding/control.go
  pkg/controllers/cassandra/rolebinding/control_test.go
  pkg/controllers/cassandra/service/control.go
  pkg/controllers/cassandra/service/control_test.go
  pkg/controllers/cassandra/serviceaccount/control.go
  pkg/controllers/cassandra/serviceaccount/control_test.go
  pkg/controllers/executor.go
Labels: approved, lgtm, release-note-none, size/L

#279 Add shortName for cassandracluster
  hack/e2e.sh
  pkg/registry/navigator/cassandracluster/etcd.go
  pkg/registry/navigator/escluster/etcd.go
Labels: approved, lgtm, release-note-none, size/S

#256 Add CreateNodePool and ScaleOut actions for Cassandra
  docs/cassandra.rst
  hack/e2e.sh
  internal/test/util/generate/generate.go
  pkg/controllers/cassandra/actions/create_nodepool.go
  pkg/controllers/cassandra/actions/create_nodepool_test.go
  pkg/controllers/cassandra/actions/scaleout.go
  pkg/controllers/cassandra/actions/scaleout_test.go
  pkg/controllers/cassandra/cassandra.go
  pkg/controllers/cassandra/cluster_control.go
  pkg/controllers/cassandra/cluster_control_test.go
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/nodepool/nodepool_test.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/service/control.go
  pkg/controllers/cassandra/testing/gen.go
  pkg/controllers/cassandra/testing/testing.go
Labels: approved, lgtm, release-note-none, size/XL

#302 Move to quay.io for image hosting
  .gitlab-ci.yml
  .travis.yml
  Makefile
  contrib/charts/navigator/values.yaml
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
  hack/e2e.sh
  hack/testdata/values.yaml
Labels: approved, lgtm, release-note, size/M

#303 Update image references for v0.1.0-alpha.1 release
  contrib/charts/navigator/values.yaml
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
Labels: approved, lgtm, release-note-none, size/XS

#292 Use new unit test fixture for pilot control tests
  docs/supplementary-resources.rst
  pkg/controllers/cassandra/pilot/pilot.go
  pkg/controllers/cassandra/pilot/pilot_test.go
Labels: approved, lgtm, release-note-none, size/L
