Repository jetstack/navigator, pull requests merged in 2018-05, with the labels that each got.

#340 Bump version numbers for v0.1.0
  contrib/charts/navigator/values.yaml
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
Labels: approved, lgtm, release-note-none, size/XS

#334 Configure Cassandra nodes to lookup their IP address by their fully qualified domain name
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/service/control.go
Labels: approved, lgtm, release-note-none, size/M, stability

#333 Remove broken host map subset assertions from nodetool
  hack/e2e.sh
  pkg/cassandra/nodetool/nodetool.go
  pkg/cassandra/nodetool/nodetool_test.go
Labels: approved, feature/upgrade, lgtm, release-note-none, size/L, stability

#301 Allow pausing clusters
  docs/cassandra.rst
  docs/elasticsearch.rst
  docs/paused-clusters.rst
  docs/quick-start/cassandra-cluster.yaml
  docs/quick-start/es-cluster-demo.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/helpers.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/controllers/cassandra/cassandra.go
  pkg/controllers/cassandra/cluster_control.go
  pkg/controllers/elasticsearch/cluster_control.go
Labels: approved, lgtm, release-note, size/L
