Repository jetstack/navigator, pull requests merged in 2018-04, with the labels that each got.

#312 Update comments throughout ElasticsearchCluster update_version action
  pkg/controllers/elasticsearch/actions/update_version.go
Labels: approved, lgtm, release-note-none, size/M

#309 Identify statefulsets by labels rather than error prone name parsing
  docs/quick-start/cassandra-cluster.yaml
  hack/e2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/seedlabeller/control_test.go
  pkg/controllers/cassandra/testing/testing.go
  pkg/controllers/cassandra/util/util.go
Labels: approved, lgtm, release-note-none, size/M

#294 Remove cassandra test framework
  pkg/controllers/cassandra/testing/testing.go
Labels: approved, lgtm, release-note-none, size/L

#317 Only scaleout if all current pods are ready
  Gopkg.lock
  pkg/controllers/cassandra/actions/scaleout.go
  pkg/controllers/cassandra/actions/scaleout_test.go
Labels: approved, lgtm, release-note-none, size/L

#327 Move Cassandra Cluster labels to the versioned API package
  pkg/apis/navigator/v1alpha1/types.go
  pkg/controllers/cassandra/nodepool/nodepool.go
  pkg/controllers/cassandra/util/util.go
Labels: approved, lgtm, release-note-none, size/S

#332 Use the pure Java kubernetes-seedprovider
  Dockerfile.pilot-cassandra
Labels: approved, lgtm, release-note-none, size/XS

#311 Cleanup API surface
  hack/testdata/cass-cluster-test.template.yaml
  hack/testdata/es-cluster-test.template.yaml
  internal/test/util/generate/generate.go
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/defaults.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/v1alpha1/zz_generated.defaults.go
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/validation/cassandra_test.go
  pkg/apis/navigator/validation/elasticsearch.go
  pkg/apis/navigator/validation/elasticsearch_test.go
  pkg/apis/navigator/validation/generic.go
  pkg/apis/navigator/validation/generic_test.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/cassandra/nodetool/nodetool_test.go
  pkg/controllers/cassandra/actions/scaleout.go
  pkg/controllers/cassandra/cluster_control.go
  pkg/controllers/cassandra/cluster_control_test.go
  pkg/controllers/cassandra/nodepool/nodepool_test.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/testing/gen.go
  pkg/controllers/cassandra/testing/testing.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
  pkg/controllers/elasticsearch/actions/create_pilot.go
  pkg/controllers/elasticsearch/actions/scale_test.go
  pkg/controllers/elasticsearch/actions/update_version.go
  pkg/controllers/elasticsearch/actions/update_version_test.go
  pkg/controllers/elasticsearch/cluster_control.go
  pkg/controllers/elasticsearch/configmap/resources.go
  pkg/pilot/elasticsearch/v5/controller.go
  pkg/pilot/elasticsearch/v5/controller_test.go
  pkg/pilot/elasticsearch/v5/process.go
  pkg/pilot/genericpilot/controller.go
  pkg/pilot/genericpilot/hook/hook.go
  pkg/util/api/elasticsearch.go
  pkg/util/api/elasticsearch_test.go
  pkg/util/ptr/util.go
Labels: approved, lgtm, release-note-none, size/XXL

#338 Add GOFLAGS option to makefile
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#337 Use cgroup for jvm memory limit
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/common/common.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
Labels: approved, lgtm, release-note, size/S

#329 Use ordered pod management
  docs/cassandra.rst
  pkg/controllers/cassandra/nodepool/resource.go
Labels: approved, lgtm, release-note-none, size/S

#342 Use consistent command line help summary for all Navigator CLI tools
  cmd/apiserver/start.go
  cmd/controller/start.go
  cmd/pilot-cassandra/pilot.go
  cmd/pilot-elasticsearch/pilot.go
Labels: approved, lgtm, release-note-none, size/M

#336 Change cassandra seed provider to jetstack/cassandra-kubernetes-seed-provider
  Dockerfile.pilot-cassandra
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/pilot/cassandra/v3/pilot.go
Labels: approved, lgtm, release-note, size/S
