Repository jetstack/navigator, pull requests merged in 2018-02, with the labels that each got.

#241 Refactor Elasticsearch node pool controller into Actions structures
  Gopkg.lock
  hack/e2e.sh
  internal/test/unit/framework/state_fixture.go
  internal/test/unit/framework/state_fixture_test.go
  internal/test/util/contains.go
  internal/test/util/contains_test.go
  internal/test/util/generate/generate.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/controllers/elasticsearch/actions/create_nodepool.go
  pkg/controllers/elasticsearch/actions/create_pilot.go
  pkg/controllers/elasticsearch/actions/scale.go
  pkg/controllers/elasticsearch/actions/scale_test.go
  pkg/controllers/elasticsearch/actions/update_version.go
  pkg/controllers/elasticsearch/actions/update_version_test.go
  pkg/controllers/elasticsearch/actions/util.go
  pkg/controllers/elasticsearch/actions/util_test.go
  pkg/controllers/elasticsearch/cluster_control.go
  pkg/controllers/elasticsearch/elasticsearch.go
  pkg/controllers/elasticsearch/nodepool/controller.go
  pkg/controllers/elasticsearch/serviceaccount/controller.go
  pkg/controllers/elasticsearch/util/nodepool.go
  pkg/controllers/elasticsearch/util/util.go
  pkg/controllers/executor.go
  vendor/github.com/kr/pretty/.gitignore
  vendor/github.com/kr/pretty/License
  vendor/github.com/kr/pretty/Readme
  vendor/github.com/kr/pretty/diff.go
  vendor/github.com/kr/pretty/diff_test.go
  vendor/github.com/kr/pretty/example_test.go
  vendor/github.com/kr/pretty/formatter.go
  vendor/github.com/kr/pretty/formatter_test.go
  vendor/github.com/kr/pretty/pretty.go
  vendor/github.com/kr/pretty/zero.go
  vendor/github.com/kr/text/License
  vendor/github.com/kr/text/Readme
  vendor/github.com/kr/text/cmd/agg/doc.go
  vendor/github.com/kr/text/cmd/agg/main.go
  vendor/github.com/kr/text/cmd/agg/num.go
  vendor/github.com/kr/text/cmd/agg/string.go
  vendor/github.com/kr/text/colwriter/Readme
  vendor/github.com/kr/text/colwriter/column.go
  vendor/github.com/kr/text/colwriter/column_test.go
  vendor/github.com/kr/text/doc.go
  vendor/github.com/kr/text/indent.go
  vendor/github.com/kr/text/indent_test.go
  vendor/github.com/kr/text/mc/Readme
  vendor/github.com/kr/text/mc/mc.go
  vendor/github.com/kr/text/wrap.go
  vendor/github.com/kr/text/wrap_test.go
Labels: approved, area/elasticsearch, lgtm, release-note, size/XXL

#245 Add kubernetes-cassandra seed provider
  Dockerfile.pilot-cassandra
  contrib/charts/navigator/templates/rbac.yaml
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/role/control.go
  pkg/pilot/cassandra/v3/pilot.go
Labels: approved, lgtm, release-note, size/M

#255 Add datacenter and rack info to cassandra nodepool spec
  docs/quick-start/cassandra-cluster.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/registry/navigator/cassandracluster/strategy.go
Labels: approved, lgtm, release-note, size/L

#259 Add myself as approver
  OWNERS
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#261 Update readme
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/M

#258 Remove cassandra chart
  contrib/charts/cassandra/.helmignore
  contrib/charts/cassandra/Chart.yaml
  contrib/charts/cassandra/templates/NOTES.txt
  contrib/charts/cassandra/templates/_helpers.tpl
  contrib/charts/cassandra/templates/cassandracluster.yaml
  contrib/charts/cassandra/values.yaml
  hack/e2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  hack/testdata/values_cassandra.yaml
Labels: approved, lgtm, release-note, size/L

#244 Add a CassandraCluster.Version field
  docs/quick-start/cassandra-cluster.yaml
  hack/e2e.sh
  hack/testdata/cass-cluster-test.template.yaml
  pkg/apis/navigator/types.go
  pkg/apis/navigator/v1alpha1/types.go
  pkg/apis/navigator/v1alpha1/zz_generated.conversion.go
  pkg/apis/navigator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/navigator/validation/cassandra.go
  pkg/apis/navigator/validation/cassandra_test.go
  pkg/apis/navigator/validation/elasticsearch.go
  pkg/apis/navigator/validation/elasticsearch_test.go
  pkg/apis/navigator/validation/generic.go
  pkg/apis/navigator/validation/generic_test.go
  pkg/apis/navigator/zz_generated.deepcopy.go
  pkg/controllers/cassandra/nodepool/resource.go
  pkg/controllers/cassandra/nodepool/util.go
Labels: approved, lgtm, release-note-none, size/L
